 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/explores", type: :request do
  
  # Explore. As you add validations to Explore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Explore.create! valid_attributes
      get explores_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      explore = Explore.create! valid_attributes
      get explore_url(explore)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_explore_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      explore = Explore.create! valid_attributes
      get edit_explore_url(explore)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Explore" do
        expect {
          post explores_url, params: { explore: valid_attributes }
        }.to change(Explore, :count).by(1)
      end

      it "redirects to the created explore" do
        post explores_url, params: { explore: valid_attributes }
        expect(response).to redirect_to(explore_url(Explore.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Explore" do
        expect {
          post explores_url, params: { explore: invalid_attributes }
        }.to change(Explore, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post explores_url, params: { explore: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested explore" do
        explore = Explore.create! valid_attributes
        patch explore_url(explore), params: { explore: new_attributes }
        explore.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the explore" do
        explore = Explore.create! valid_attributes
        patch explore_url(explore), params: { explore: new_attributes }
        explore.reload
        expect(response).to redirect_to(explore_url(explore))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        explore = Explore.create! valid_attributes
        patch explore_url(explore), params: { explore: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested explore" do
      explore = Explore.create! valid_attributes
      expect {
        delete explore_url(explore)
      }.to change(Explore, :count).by(-1)
    end

    it "redirects to the explores list" do
      explore = Explore.create! valid_attributes
      delete explore_url(explore)
      expect(response).to redirect_to(explores_url)
    end
  end
end
